{% set name = "scriptengine" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scriptengine-{{ version }}.tar.gz
  sha256: 78f7a41c7cfdd79d5488b5a186c5244b7cc02c0cd58c3a21b710786870b54468

build:
  entry_points:
    - se = scriptengine.cli.se:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=60
  run:
    - python >={{ python_min }}
    - python-dateutil
    - pyyaml
    - jinja2
    - deepmerge

test:
  imports:
    - scriptengine
  commands:
    - pip check
    - se --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/uwefladrich/scriptengine
  summary: A lightweight and extensible framework for executing scripts written in YAML
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - uwefladrich
