{% set name = "scriptengine" %}
{% set version = "0.12.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scriptengine-{{ version }}.tar.gz
  sha256: 3de033c996a14bd836d73ff6bb3d4a80352e0555e6a2e94621a531f3457caee5

build:
  entry_points:
    - se = scriptengine.cli.se:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - deepdiff >=5.7.0,<6.2.1
    - deepmerge
    - jinja2
    - python >=3.6
    - python-dateutil
    - pyyaml

test:
  imports:
    - scriptengine
  commands:
    - pip check
    - se --help
  requires:
    - pip

about:
  home: https://github.com/uwefladrich/scriptengine
  summary: A lightweight and extensible framework for executing scripts written in YAML
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - uwefladrich
    - zklaus
